name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: Setup npm
        run: |
          npm set @danji:registry=https://npm.pkg.github.com/danji
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}"

      - name: Configure Git User
        run: |
          git config --global user.email "erangerang15@gmail.com"
          git config --global user.name "Danji-ya"

      - name: Install dependencies
        run: yarn install

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          git stash
          git checkout ${{ github.ref }}
          if [ ${{ github.base_ref }} = development ]; then
            lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            lerna version --conventional-commits --conventional-graduate --yes
          fi
            lerna publish from-git --yes

      - name: Publish
        run: |
          lerna publish --yes
