name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Add GiHub Package Token
        run : echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }}" > ~/.npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: Install Dependencies
        run: yarn install

      - name: Deploy new Package
        run: yarn run publish
        env:
          GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}